### ISSUE TITLE
Run commands on game actions

### ISSUE THREAD

**Issue by daboross** [SkyWars/SkyWars#220]
This shouldn't evolve into a scripting situation, all this should do is allow a few simple commands to be executed when a player joins the queue, and when the game is finished.

Configuration format should be:

```yaml
# 
run-commands-on:
    queue-join:
    # For queue-join, @p will be replaced with the name of the player who joined
    - command1 @p
    - command2 @p
    game-end:
    # For game-end, each command will be run once for each winner, and @p will be replaced with the name of that specific winner
    # This will only run once for non-team games, but be warned it will run multiple times when teams are enabled
    # These commands will be run 1 second after players are teleported back and all items saved are restored.
    - give @p log 1
```
